### ISSUE TITLE
Running user code

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#102]
At some point we would like to run user code. 

**If this is deployed anywhere we need to have serious validation on what can and cannot run.** As long as we are sending user code through a request to our server to run it, we need to make sure that unsafe code cannot be run.

Restricted Python seems like a good solution for the scale of this project. It runs the given Python code in a safer mode where certain code is restricted (imports, sys, access to file system, etc...). We could also perform some of our own sanitization even before that.

As long as this is deployed and we are sending the code to run over API requests, we need some protection. Alternatively, we can always use Node's childProcess.

**Comment by MajeedKazemi** [comment]
urgency: 1
dependency: 1

**Comment by MajeedKazemi** [comment]
Should handle `hole`s properly before running code.

**Comment by MajeedKazemi** [comment]
done in a1c3ee8e4d87988e9da898d19e181d4215b41826
