### ISSUE TITLE
Warnings: Finalize the warning system

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#111]
Some warnings need to be split and fine grained (more specific information needs to be given). Others such as type checks and the type system in general need to be updated to support nested expressions and a variety of special cases. 

we also need to finalize the messages.

**Comment by MajeedKazemi** [comment]
urgency: 3
dependency: 1

**Comment by vicchig** [comment]
Hover warnings have been reworked and merged with the draft system. Other places where they are now used include highlighting variable references of variables that do not exist and other similar cases. Pop-up notifications are what will be mostly used to indicate invalid actions to the user going forward.
