### ISSUE TITLE
Typed Empty Expressions need to remember their initial type after they have been replaced with a literal or some other expression

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#119]
When a Typed Empty Expression is replaced by another expression with a different type, the old type needs to be remembered somehow. Otherwise we have no way of knowing what the type of hole to put back in case we delete the expression/literal we inserted.

Ex.:

print() accepts type Any as the type of its argument. However, print(123) will change this to a literal of type Number. However, when we go to delete the entire literal, what should the type of the TypedEmptyExpression that will be replacing the literal be? It should be Any, but this needs to be recorded somewhere in some way.

**Comment by MajeedKazemi** [comment]
urgency: 2
dependency: 4 (delete depends on this)

**Comment by MajeedKazemi** [comment]
no longer needed. will keep a mapOf<index, data-type> for this.
