### ISSUE TITLE
Type Inference

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#120]
Need to refine the type inference system. Have to well-define cases where types change and what they need to change to as well as type constraints on code constructs.

Examples:
  An expression needs to take on the type of its contents which needs to be verified against the type of the parent expression if it has one. So in ((--- + ---) + 123), the inner addition on the left should only accept numbers, even though strings are also technically allowed under normal circumstances.

**Comment by vicchig** [comment]
#79

**Comment by MajeedKazemi** [comment]
urgency: 4
dependency: 3 (at least for the type-based editing)
