### ISSUE TITLE
Draft Mode

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#121]
We need a draft mode where we could allow the user to enter code that is midway between being correct and completely broken. It is something that is not correct by itself if we were to run the program, but something that should still be allowed because it could become correct with further input. 

The warning system should also probably highlight these cases.

Examples of this could include:
  Inserting a string literal in an if-statement's condition. Something that is not allowed by the current type system, but should be allowed since the string could be then made part of a comparator such as "abc" == strVar.

**Comment by MajeedKazemi** [comment]
urgency: 3
dependency: 3 (will affect how we want to implement the text-based editing of expressions at least)

it requires other things to change a lot (type-checking and many other places)

**Comment by vicchig** [comment]
This will be the parent issue of the draft mode feature. I have created the following issues in order to organize the work that needs to be done. 

- #172

**Comment by MajeedKazemi** [comment]
is being handled in #214

**Comment by MajeedKazemi** [comment]
I think we can close this issue, @vicchig right?

**Comment by vicchig** [comment]
> 
> 
> I think we can close this issue, @vicchig right?

Some related issues like #193 and #194 are not done, but this one could probably be closed.

**Comment by MajeedKazemi** [comment]
Yes, lets do nested draft mode later on.
