### ISSUE TITLE
merge validations into a separate validation.ts file

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#123]
- `isValidElseInsertion()`
- `isValidReference()`
- `isAbleToInsertComparator()`
- `getValidVariableReferences()`
- `getAllValidInsertsMap()`
- `getAllValidInsertsMap()`
- `getValidInsertsFromSet()`
- `tryInsert()`

**Comment by vicchig** [comment]
Validations have been completely reworked. The code is in the new-variables branch. The main changes are:

- refactored tryInsert() into action-filter.ts
- refactored insert() into various code construct behaviours (typeValidateInsertionIntoHole for example) and action-executor actions
- other validation was moved into various places such as type-checker.ts, validator.ts, action-filter.ts and action-executor. 
- new action validation was added to event-router.ts
