### ISSUE TITLE
Delete Functionality

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#126]
1. Need to add the ability to delete code constructs. This needs to cover:

- Deleting Expressions (literals, binary, unary, etc...)
- Deleting Statements (empty line, var assignment, function calls, control statements, etc...)
- Deleting the entirety of the program's code by doing Ctrl+A + Backspace?

2. Constructs, when deleted, need to be replaced by an appropriate construct. In the case of statements it will be empty lines; in the case of expressions it would by either a Typed Empty Expression or an Empty Expression.

3. These actions need to be routed through the Action Stack as well in order to have the option to undo them.

**Comment by MajeedKazemi** [comment]
urgency: 5
dependency: 1

**Comment by MajeedKazemi** [comment]
same as #11

**Comment by MajeedKazemi** [comment]
things that needs to be considered for implementing the delete:
- keeping the current insert architecture (replacing holes with other tokens and expressions)
  -  when something is being deleted, we need to know what that thing was to replace it
    - `print(randint(10, 40|))` => if the user presses backspace => `randint(` + `10` + `, ` + `40` + `)` => needs to simply know that as we're removing randintExpr.tokens[3], then that thing's parent => randintExpr => needs to somehow keep information about what to replace it with. and because we have the index, things should be alright.
  - but what will happen to the type checkers? this is a quesiton for @vicchig => is it enough for the type checkers so that it retains its previous TypedEmptyExpression's type? or does it need more information?
- what if we did not replace empty holes, and add things as children nodes to them?
  - some problems might arise with the `getContext()` function.

**Comment by vicchig** [comment]
>       * but what will happen to the type checkers? this is a quesiton for @vicchig => is it enough for the type checkers so that it retains its previous TypedEmptyExpression's type? or does it need more information?


If we are removing a hole that has been filled in, then we already know what type of TypedEmptyExpr to replace it with. In the example you give you are deleting the hole that has 40 in it, which means the TypedEmptyExpr that will replace it must be a number. 

I think that is all we need. Because the type system already checks it when everything is being inserted so we are safe to assume that if there is a number somewhere and we replace it with a TypedEmptyExpr, then the expression should also be of type number.

The trickier part are the cases where an operator or argument can accept multiple types. 

- +
- - (1 + 2) and delete 1 or 2 => (1 + NUM) or (NUM + 2)
- - (1 + NUM) or (NUM + 2) and delete the number => (STR/NUM + STR/NUM)
- len()
- - Can accept the following types: AnyList, BooleanList, NumberList, StringList, String
- - len(obj of one of the types above) => len(AnyList/BooleanList/NumberList/StringList/String) 

There are other examples such as this one, but they are all similar to the two cases above.

**Comment by MajeedKazemi** [comment]
So basically we won't be able to always use its current value. e.g. inside a print which accepts `any`. Am I right @vicchig ?

**Comment by vicchig** [comment]
@MajeedKazemi 

Yeah it is only possible for holes that accept a single type to begin with, but this is still a good shortcut in some cases.There is no one solution for this because it depends on context. A solution that stores the type in the parent won't work for my first example with the + operator either. 

To make this easier in the cases where we delete the last non-empty hole within an expression and in doing so returning it to its default state, we could maintain a map that links a code construct to the types each of its holes holds by default. So + would map to [[str, int], [str, int]]. For method arguments this list would be parallel so that the type of the first argument to a multi-argument method would be the first list in the mapping.
