### ISSUE TITLE
move all insertions into another file

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#128]
after the validation is separated, we can move all insertions into the `editor.ts` file

**Comment by MajeedKazemi** [comment]
urgency: 2
dependency: 4

**Comment by MajeedKazemi** [comment]
=> separating all `executeEdits()` calls from the insert method :)

**Comment by vicchig** [comment]
insert() was removed completely. Now the code for inserting a construct is split between the construct implementation, event-router and action-executor.
