### ISSUE TITLE
Defining imports

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#130]
Some functions such as randint() are contained within modules that are not part of a standard Python program and need to be imported. When the user uses these functions we need to automatically import the required module to make the program compile without error when the time comes. 

The amount of function calls and other constructs that will depend on this is currently small (just randint() at this moment). Therefore, an easy and quick solution would be to keep a map of Construct -> Import Module/Import Statement that we could easily access in order to add the correct import to the program.

**Comment by MajeedKazemi** [comment]
urgency: 1
dependency: 1

**Comment by MajeedKazemi** [comment]
fixed by @vicchig
