### ISSUE TITLE
decompose if/elif/else statements

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#133]
It seems that we do not need to keep these in a tree structure within the parent if statement. we can simply have the elif and else statements as separate statements below each other in their parent's body.
- validator: needs to determine valid inserts of `elif` and `else`.
- remove `isValidReference()` and merge it with the rest of the scope functionalities.

**Comment by vicchig** [comment]
These constructs have been decomposed. They are not part of the same tree structure within the AST anymore. They are each an individual AST node.
