### ISSUE TITLE
keeping all variable assignments in the scope list, to track variable type changes

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#134]
Python allows types to change when variables are reassigned, therefore, we need to track the type changes in order to properly provide validation warnings or suggestions to the user.

**Comment by vicchig** [comment]
Addressed by the changes made in the new-variables branch. Now the type of variable is calculated based on the assignments above the line we are trying to calculate it on. This allows types to be dynamic.
