### ISSUE TITLE
Draft Mode Prototype: Visual indication that a construct is in draft mode

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#173]
Each expression/line that is in draft mode should provide the user with a clear visual indication of the fact that this code construct is in draft mode.

For the prototype:
- Highlight the code construct/line that is in draft mode.
    - Place a span or div element with a negative z-index on that line/behind the expression.
    - This area will be highlighted with some colour in order to reflect that it is different from other code.
- Expressions/statements that become valid within the draft mode need to be highlighted in green. Depends on #176 and #193

**Comment by MajeedKazemi** [comment]
This is done, right? @vicchig

**Comment by vicchig** [comment]
> 
> 
> This is done, right? @vicchig

Yes
