### ISSUE TITLE
ES Version Upgrade

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#186]
We are currently using ES5 2015. Consider upgrading to ES6 so that some modern features are available to us such as iterating over the keys of a map.

Once this is done, could refactor how suggestions-controller and other places iterate over maps and greatly simplify a lot of that code.

**Comment by MajeedKazemi** [comment]
Yeah, lets do this. I think that I just used an old boilerplate from monaco.

it seems that these two lines from `.tsconfig` need to change: 
- `"target": "es5"`
- `"lib": ["dom", "es5", "es2015.collection", "es2015.promise"]`

**Comment by MajeedKazemi** [comment]
Added in #404f0e31c078057f3d712f3979c5c08e4734f9c5
