### ISSUE TITLE
New Variables

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#233]
- We would have the following main items for variables:
  - a merged var definition and reassignment: `--- = ---` with a different type of hole for the left and right.
  - a reassignment for an indexed variable: `---[---] = ---`
  - a scope-aware box for all user-defined variables and functions:
    - references with their types along with index references for list types: `---` and `---[---]`
   
- Merge *creating variables* + *reassigning variables*
  - An action needs to be done in order for the variable to be completely created (and have a button in the toolbox)
    - actions: change of focus, pressing enter/esc
  - What happens in the AST?
    - how to differentiate between variable definition and assignment?
  - What kind of updates need to happen?
    - update the types
    - renames => we could attach callbacks to every new variable reference
      - could also store all variable references to each var in a map inside module
    - deleting a variable

- the hierarchical menus would include:
  - all method calls
  - all variable actions such as `+=`, `-=`, and etc.
  - index versions of the previous things.

**Comment by vicchig** [comment]
**Depends on:**

- #238 
- #239
- #240
- #241
- #242
