### ISSUE TITLE
Add event callbacks on code constructs

### ISSUE THREAD

**Issue by hayatpur** [MajeedKazemi/nova-editor#26]
Add ability to subscribe to events on changing, replacing, or deleting a code construct. 

```javascript
code : CodeConstruct
callback : () => {...}

code.onChange.subscribe(callback)
code.onReplace.subscribe(callback)
code.onDelete.subscribe(callback)
```

**Comment by MajeedKazemi** [comment]
As only the parent node is able to understand if its internal tokens/expressions have been replaced/changed, they will be the code-constructs that will fire the `onReplace` and `onDelete` events.
