### ISSUE TITLE
Bug: should close draft mode when deleting modifiers that create them

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#277]
![image](https://user-images.githubusercontent.com/57059538/128890266-bb0b6a03-71bf-499c-b697-f56cd8cd1ecc.png)
becomes ->
![image](https://user-images.githubusercontent.com/57059538/128890174-c9b42b61-03dd-4f1f-b4b1-e3cc989d7b40.png)

**Comment by vicchig** [comment]
Seems like this was fixed. I could not reproduce it.

**Comment by vicchig** [comment]
Closing since the issue has not reappeared.
