### ISSUE TITLE
Bug: sometimes can't use enter to execute the selected item in the autocomplete menu

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#298]
Such as here:
![image](https://user-images.githubusercontent.com/57059538/130110540-9053d4c9-b86b-4be8-860b-3d411ec619b1.png)

Although I was able to place the `!=` operator by pressing the terminating char: `=`

**Comment by vicchig** [comment]
This happens because `performMatchAction()` inside of action-executor.ts is not called for options that are selected from the autocomplete menu. It seems like it should be being called for these as well.

**Comment by MajeedKazemi** [comment]
this is working for me
