### ISSUE TITLE
Focus: Focus is not correctly updated for certain insertions

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#303]
The cursor in the image below is at the end of the fifth line instead of being focused on the hole of the statement on that line. This occurs after the entire statement is inserted from the toolbox and probably when these statements are inserted by other sources as well.

![image](https://user-images.githubusercontent.com/44914019/130481675-1b62e1b1-b8da-4039-ad7d-c7d64fe4cfd0.png)

**Comment by MajeedKazemi** [comment]
same as #287

**Comment by vicchig** [comment]
Closing duplicate.
