### ISSUE TITLE
Autocomplete: Duplicate assignment option is shown for existing variables in the autocomplete menu

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#304]
This is likely because we have VarAssignmentStmt and an AssignmentModifier. Should only one of them should be included in the autocomplete?

EDIT: This is actually a bit tricky. We need the AssignmentModifier for suggestions coming from the menu created when Ctrl+Space are pressed so that we can differentiate an assignment to an existing variable from a creation of a completely new variable which is only done with VarAssignmentStmt. 

The problem is that both of these show up when the user types in an identifier for an existing variable. 

![image](https://user-images.githubusercontent.com/44914019/130487375-2a3725f2-2a14-4e53-a96b-618ecec200b0.png)

**Comment by MajeedKazemi** [comment]
one simple solution (or hack as you mentioned today) would be to simply filter for unique items based on their `optionName`.

**Comment by vicchig** [comment]
> 
> 
> one simple solution (or hack as you mentioned today) would be to simply filter for unique items based on their `optionName`.

We need both options to be displayed though. One of them should just not say `p = ---` and say `var = ---` instead. I ended up adding a check for whether the entered text is an identifier of an existing variable.
