### ISSUE TITLE
a new `import` item button

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#319]
### how it should work:
- will simply add that import to the top of the program
- new code constructs will be included in the toolbox and autocomplete after the import was successful

### design questions?
- how should the user know that in order to use randint (that doesn't exist in the toolbox), they need to import something? (should it work similar to a cascaded menu?)
- do we want to also include it in the autocomplete?
- should they all have their own category?

**Comment by vicchig** [comment]
#360
