### ISSUE TITLE
bug: for loop iterator not available when the for is at the first line

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#343]
![image](https://user-images.githubusercontent.com/57059538/132583760-b685535a-c468-49cf-9f6a-70716737efcd.png)

**Comment by vicchig** [comment]
@MajeedKazemi could you please provide the exact actions that trigger this. I have tried a lot of different actions, but `i` was always available.

**Comment by MajeedKazemi** [comment]
Wasn't able to reproduce it either... weird bug!

**Comment by vicchig** [comment]
Closing this as it was not reproducible on master. Open a new issue if the bug is ever reproduced.
