### ISSUE TITLE
Vercel Deployment: Environment variables need to be set on Vercel for deployments to pass

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#358]
Currently deployments will fail because vercel likely does not have the environment set up. We need to add our environment variables to versel. It should have an option like that. Most hosting platforms do.

**Comment by vicchig** [comment]
@MajeedKazemi this is not urgent, but if we are planning on demoing the app, this needs to be done before that.

**Comment by MajeedKazemi** [comment]
@vicchig added env vars to Vercel.
