### ISSUE TITLE
Import Statement: EditableTxtToken navigation misses initial hole selection

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#361]
For IdentifierTkn when you navigate to them initially, the entire hole gets selected. This is not the case with EditableTxtTkns which makes them feel weird to use. I know this is the intended design, but I think we need to think about how to address this issue. Either by changing the navigation behaviour for them or by creating a new token that implements the desired behaviour.

**Comment by MajeedKazemi** [comment]
@vicchig please check 7b3531b60a8e9af47e30bf371dfa253169b7baac and see if this fixes this issue

**Comment by vicchig** [comment]
> 
> 
> @vicchig please check [7b3531b](https://github.com/MajeedKazemi/nova-editor/commit/7b3531b60a8e9af47e30bf371dfa253169b7baac) and see if this fixes this issue

@MajeedKazemi it did, closing this.
