### ISSUE TITLE
Events: Ctrl+Space being pressed twice in sequence opens default monaco suggestions

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#382]
This needs to be disabled. I think we might have forgotten to stop event propagation once we catch it.

![image](https://user-images.githubusercontent.com/44914019/134388635-975e29a3-7bff-4916-a396-fa24bf3cf3f3.png)

**Comment by MajeedKazemi** [comment]
This is interesting. Do we even need the ctrl+space menu?

I don't remember the final decision on this. 

I personally believe that it's good to be able to control these things, however, it is important to provide all the required training wheels *automatically*. therefore, one design is to forget about the ctrl+space and just show the menu whenever a user navigates into an expression hole.
