### ISSUE TITLE
Toolbox Constructs: replace() should take two arguments (at least)

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#390]
Currently `replace()` (under Text) is displayed to have only one argument, but it actually needs two. The first argument is the value to replace and the second is the value to replace with.

**Comment by MajeedKazemi** [comment]
![image](https://user-images.githubusercontent.com/57059538/137628131-03c471d4-3403-465d-88a4-31487db81ea9.png)
![image](https://user-images.githubusercontent.com/57059538/137628152-ff2f66ef-2d7e-4ddc-b1ea-f55d318f2d28.png)
![image](https://user-images.githubusercontent.com/57059538/137628170-edd7aa69-7d97-496c-88d9-1181cbd4156a.png)

seems that it's fine.
