### ISSUE TITLE
Feature: Successful autocompletes should focus the next available empty hole

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#391]
When the user is successfully using the autocomplete it could be annoying to interrupt their typing to make them click on the next hole to fill. What if instead them having to switch off the keyboard to the mouse to click the next hole, we did it automatically for them. So after each successful autocompletion we would navigate them to the next hole to fill.

**Comment by vicchig** [comment]
@MajeedKazemi what do you think?

**Comment by MajeedKazemi** [comment]
so I would say the user might not always want to do that:
in the case of expressions, I guess, sometimes users want to chain the expr with some other modifier/expr.

for example: `while ( --- = ---) :`

and the user enters a variable identifier in the first hole => and they actually wanted to follow that variable with a `+ 10`.

**Comment by vicchig** [comment]
I see. Yeah that does make sense. It would probably be more annoying than helpful.
