### ISSUE TITLE
Validation: Modifier Deletion is only identified if there is exactly one modifier on an expression

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#404]
For example, if we have the following code:
```
abc = "str"
if (abc.find() and  ---)
```
And we then delete the `.find()`, the code will correctly identify the type change from Number to Text and create a draft mode message.

However, if we do this with multiple modifiers nothing will happen. That case is either not handled or has a bug in it because going from `abc.replace().find()` to `abc.replace()` does not create a draft mode warning in holes where a string is not expected.

**Comment by MajeedKazemi** [comment]
priority: 2
difficulty: ??
