### ISSUE TITLE
Toolbox: Draft mode buttons are not filled with draft mode colour in cascaded menus

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#408]
The button for abc is yellow in the toolbox variable section. The button for a string literal is also yellow, but in the cascaded menu it appears as a valid button even though if you click it, it will trigger (and it should) the draft mode.

![image](https://user-images.githubusercontent.com/44914019/137152662-482e9aec-9ea6-4ff5-9c70-cf084c34c7f8.png)

**Comment by MajeedKazemi** [comment]
priority: 4
difficulty: 1.5

**Comment by vicchig** [comment]
Fixed in #420
