### ISSUE TITLE
Autocomplete Menu: Menu does not scroll up when using arrow keys to move down and have mouse cursor on one of the options

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#409]

**Comment by MajeedKazemi** [comment]
how to replicate this?

**Comment by vicchig** [comment]
The issue did not have to do anything with the mouse being on top of another option in the menu. Instead, it was an off by one error in the update of the end of the range of options that is being shown when the focused option is reset to the top option when moving down in the menu.

To replicate:
 1. Insert a print on an empty line.
 2. Navigate to the hole of the print and open a long enough autocomplete menu (Ctrl + Space) to require scrolling.
 3. Step through the menu until the end so that the menu wraps around.
 4. Continue stepping and observe how the focused option disappears off the viewport of the menu once it reaches the end. 

Fixed in #419
