### ISSUE TITLE
Cannot exit indented blocks with arrow keys

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#44]
**Description:**
User cannot use arrow keys to exit indented blocks of code.

**Severity: 2**

**Steps to Reproduce:**
  1. Insert any code that requires indents such as an if-statement
  2. Try to navigate outside of the block using arrow keys
          i. Notice how you are unable to do so
  3. Click on the beginning of an empty line outside of the indented block
          i. Click throws an error
         ii. Any further edits will insert code inside the indented block regardless of cursor position

**Comment by MajeedKazemi** [comment]
fixed #110
