### ISSUE TITLE
include tooltip in toolbox for disabled actions + reason

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#450]
provide info about:
- tokens, modifiers, expressions, and statements
- types

and provide suggestions on where they could use things.

**Comment by vicchig** [comment]
@MajeedKazemi 

Identifying the exact reason is kind of hard. This might have to be a little general. Like on the level of "you cannot put a statement inside an expression".

We have the methods for validating all of it, but they largely don't differentiate the specifics which we would need to get the reason messages right.

**Comment by MajeedKazemi** [comment]
yes, if we could only do these two, then it would be great: if it's a type problem, or if it's an expression/statement/token/modifier kind of problem (which doesn't allow a particular insertion). I think that we can achieve this. right? @vicchig

**Comment by vicchig** [comment]
Yeah we would just need to add cases for creating messages for these inside of our validation methods. For draft mode insertions it should be relatively easy as we already have a place that generates them and we would have to just change the text. For invalid insertions we would have to do more work that boils down to just creating cases for handling message creation in our validation methods.
