### ISSUE TITLE
redesign the `learn` button

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#451]
instead of the current design, lets show a tooltip over each action in the toolbox (on hover):
- if disabled: quickly say why + what it does + learn button
- if enabled: quickly say what it does + learn button

this would also allow us to reduce the width of the toolbox.

**Comment by MajeedKazemi** [comment]
@vicchig thoughts?

**Comment by vicchig** [comment]
@MajeedKazemi 

I think this is good. Especially because with this the learn button would be explicitly visible and not hidden as it is now.
