### ISSUE TITLE
discussion: pressing enter within a string should insert the `\n` char

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#456]
and show a pop-up message of what actually happened.

@vicchig thoughts?

**Comment by vicchig** [comment]
@MajeedKazemi 

Do you think it could be argued that this does not help the transition or at least does not relate to it? 

This would teach the students a trick that is only available in our tool. In reality pressing `enter` within a string has a different use in an IDE. For example, when I want to split a string on multiple lines I would do "abc\ " and then move the second pair of quotations to a new line with enter and continue typing. 

We also don't do anything else with escape characters. So I would not even consider this as part of our learning moments. It would just be an editor feature.

**Comment by MajeedKazemi** [comment]
alright. makes sense. we should probably include escape characters in the toolbox so that they could insert them from there... I think that is more along the transition, right?

**Comment by vicchig** [comment]
Yes, we could definitely have them there.
