### ISSUE TITLE
being able to identify non-double quoted strings: print statements + assignments

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#457]
![image](https://user-images.githubusercontent.com/57059538/139894394-6d0835e7-b450-49f4-b0de-748c9af05e48.png)

we should provide an error message that helps the user fix this by wrapping it with a double quote.

possible methods for identifying it:
1. noticing a space between the characters of an autocomplete token
2. not being able to find any variable associated with what the user has typed into an expression hole

@vicchig we have to implement this ASAP. any thoughts on a good mechanism for identifying these errors? I think that the second method has more potential.

**Comment by vicchig** [comment]
@MajeedKazemi 

I would use option 2 and also ensure it does not match any keyword either. We can also manipulate the matching score threshold on the autocomplete string match in such a way that we can detect these by just seeing that there are not matching options as well. 

Although, it might be hard to make it accurate.


I would also differentiate the autocomplete highlight from the draft mode highlight. We need different visual feedback for those two. Right now it is extremely confusing. Even Yan was confusing the autocomplete with the draft warnings at times. Users might wonder why is it that when they hover over one of them, they get a warning and the other one does nothing.

**Comment by MajeedKazemi** [comment]
yes, we should differentiate the autocomplete highlight from the draft mode highlight.

ok. sounds good. is there a way that we could query the autocomplete and see if anything is being suggested?

**Comment by vicchig** [comment]
Yeah, we can just check if the current focused menu is empty, which is the only menu we have anyway since we are not using multiple ones anymore. 

It is something like `this.module.menuController.menus[focusedMenu].options`, but I would have to look at it to tell exactly how it is done. It should not be a problem though.

**Comment by MajeedKazemi** [comment]
no this is enough and great. thanks :) I'll try to implement it
