### ISSUE TITLE
Bug: Undefined closest line

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#467]
If you create a variable and then delete that statement and try navigating up or down, the editor crashes.

Steps to Reproduce:
1. Create a variable with an identifier and some value
2. Navigate off of the variable to create it
3. Go back and clear the variable identifier, but do not remove the statement.
4. Navigate off of the variable line.
5. Navigate back onto the line and delete the variable. 
6. Try navigating up and down. Observe the console for the error.

**Comment by MajeedKazemi** [comment]
is this really fixed in #558 ? I am still seeing the problem in the latest deployment (https://nova-editor-2o8k31olt-majeed.vercel.app/)

**Comment by vicchig** [comment]
I was unable to reproduce it locally and on the deployment. Could you let me know what exactly you are doing to cause the bug?
