### ISSUE TITLE
Bug: Unable to insert indent on line

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#471]
It seems like validation is not allowing the user to indent on a line right below a block statement that is within another block statement. So for example, if I am on line 6 of the screenshot, I cannot indent.

![image](https://user-images.githubusercontent.com/44914019/140438282-422b8a4b-48b4-4879-8534-0b0e6f5f64b9.png)

**Comment by MajeedKazemi** [comment]
yes, I was aware of this. thanks for documenting the bug. we should fix this.

**Comment by vicchig** [comment]
Sorry, I thought I checked and didn't see an issue for it, but now I also remember you telling me about it as well.
I guess we can keep this open just so that we are aware of it.
