### ISSUE TITLE
bug: for loop variable not available on first line sometimes

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#473]

**Comment by vicchig** [comment]
There's also an empty variable that is created when you create and then delete a for-loop var. It is also likely related to this.

![image](https://user-images.githubusercontent.com/44914019/140572032-9245295b-b492-491a-8600-6497ffd1cfc7.png)

**Comment by vicchig** [comment]
Found a way to reproduce this:

1. Create a for loop
2. Insert something into the SECOND hole (such as range(0, 1))
3. Now give the variable an identifier and try to use it on the first line.
