### ISSUE TITLE
variable assignment statement

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#487]
![image](https://user-images.githubusercontent.com/57059538/140625302-3e4297ef-ed5c-408c-ac9e-5067317052fd.png)

should not go into draft mode in these cases.

how to replicate:
- type variable name + dot + append

**Comment by vicchig** [comment]
@MajeedKazemi 

This one was already logged, please see #485

**Comment by MajeedKazemi** [comment]
Oh sorry about it, I'll close this one then.
