### ISSUE TITLE
Some selections result in errors

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#49]
**Description:**
Uncaught TypeError gets triggered by the ast while making various edits. It is not limited to the steps below, but these steps are the easiest and most consistent way of reproducing it.

**Severity: 2**

**Steps to Reproduce:**
  1. Create a variable and set it to either True or False
       i. Observe console error 
      ii. Window loses focus (I think this is actually due to the logging in the console. Not sure why, but whenever a message is printed there, the edit window loses focus)

**UPDATE:**
1.ii is fixed. 1.i is still an issue.

**Comment by MajeedKazemi** [comment]
fixed #110
