### ISSUE TITLE
sth.append is working as an expression, not a statement

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#514]
![image](https://user-images.githubusercontent.com/57059538/141524502-58526094-daba-46eb-b9e5-892ab0fdc174.png)
![image](https://user-images.githubusercontent.com/57059538/141524582-c1e38f64-8635-4497-a0ba-bba3e5c03ce0.png)

**Comment by vicchig** [comment]
It works as a statement as long as you go through the autocomplete :) 

![image](https://user-images.githubusercontent.com/44914019/141656254-4eabaa07-d551-4938-bedc-90c4116cacaf.png)
