### ISSUE TITLE
Should allow adding else/elif after and outside of if statements

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#52]
Although #50 was fixed. But the user still might wants to add these cases

```python
if (---):
    print()
<- else/elif
```
Just need to add an `EmptyLineStmt` after the `print()` and then insert the else there using the `insertElseStatement()` function.

```python
if (---):
    print()

<- else/elif
```
in the above example, it should also update the AST and editor's `EmptyLineStmt`s.

**Comment by vicchig** [comment]
Addressed by the if-elif-else rework.
