### ISSUE TITLE
on-insert-into for addition: should consider updating possible types when left and right types change

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#530]
![image](https://user-images.githubusercontent.com/57059538/143477002-1b1e5aee-b5b2-4cc8-814b-f3c87b563500.png)
![image](https://user-images.githubusercontent.com/57059538/143477030-6dc4c2a8-5416-41c4-8433-31136e0ebaed.png)
![image](https://user-images.githubusercontent.com/57059538/143477063-555b691a-1c30-40c8-9d5e-f574ab2eeff5.png)
![image](https://user-images.githubusercontent.com/57059538/143477089-f4205574-b629-4c96-ab06-18bc71325142.png)

**Comment by vicchig** [comment]
They are updated, but I think some code constructs use different insertion paths so the update just does not run for all of them. I will take a look and see what exactly is wrong.

**Comment by MajeedKazemi** [comment]
![image](https://user-images.githubusercontent.com/57059538/147720295-fd321788-425b-49fe-a9f1-c22fe3cb6b39.png)

inserted `x = input("asdf")` and then `print((x + 123))` the `123` was highlighted at first. then when I inserted the `int()` around the input, it is suggesting that both of them should be converted to str. I think we've had a great progress by showing both warnings. but maybe in this particular case, it should just not show any warning :)

**Comment by vicchig** [comment]
I am not sure how you are getting the warning on the `x` to appear. If I follow these exact steps only the `123` remains highlighted. It of course should not be highlighted once you insert the int. I will add that.

**Comment by vicchig** [comment]
Never mind I see. You are inserting the addition using `x+` instead of `+` followed by adding the `x` in so it is not updating the types properly because that insertion path probably does not call the update function.
