### ISSUE TITLE
Cursor gets stuck and crashes program after repeated arrow key presses

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#54]
**Description:**
Cursor navigation with arrow keys can get stuck on a specific construct and crash the program after repeated arrow key presses.

**Severity: 5**

**Steps to Reproduce:**
  1. Insert for-loop (works with while and if as well, so I think this is navigation specific, not code construct specific)
  2. Insert loop counter/variable to loop over
  3. Use a call to range() as the range to loop over. Give it some numeric range.
  4. Press right arrow key to attempt to move cursor to the end of the line.
       i. Cursor gets stuck selecting the call to range().
  5. Try moving cursor with left/right arrow keys anywhere.
       i. Error is thrown in console.
      ii. Program has to be restarted. Nothing else can be added to the code window. Text edits can be made anywhere. 

**UPDATE:**
No error is generated anymore, however it is impossible to move the cursor to the line below using arrow keys.

**Comment by MajeedKazemi** [comment]
fixed with #110
