### ISSUE TITLE
`ForStatement` calling `onInsertInto` when not actually inserting anything.

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#562]
`onInsertInto` is meant to be called when we are actually inserting something that will explicitly be part of the AST. It should not be called during validation since validation does not actually insert anything.

See `setIterator()` in ast.ts

**Comment by MajeedKazemi** [comment]
Is this what has been causing the issues for `for` statements?

**Comment by vicchig** [comment]
> 

Not sure, but it was causing errors that would complete break the editor in some cases. I have fixed it. I will close any other issues if it fixes them when I go through those.
