### ISSUE TITLE
error with redefining vars that use the same identifier with a `for` loop identifier

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#565]
1. write this program:
![image](https://user-images.githubusercontent.com/57059538/147885310-21bc3e5c-4710-4374-aa41-e985d51e86b6.png)
2. delete the `x = 123`
3. redefine `x = 123`
4. observe the error

this is not related to your new changes @vicchig it has been here previously.

**Comment by vicchig** [comment]
> 

Thanks for mentioning this. I will take a look.
