### ISSUE TITLE
Pressing Backspace during literal edits breaks navigation

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#59]
**Description:**
If you press Backspace while editing a literal's value, the cursor will be pushed out of the literal edit box (not really pushed out, it probably just stays in the position of the character it just deleted instead of moving one space left), this will break navigation once you press one of the arrow keys (left or right).

**Severity: 5**

**Steps to Reproduce:**

  1. Insert an if-statement.
  2. Insert a literal as a condition (text or numeric).
  3. Add some characters to the literal and then press backspace. 
  4. Press left arrow key and observe the error in the console. 
       i. Program is broken now. Text edits can be done anywhere.

**UPDATE:**
With new navigation the error is gone, but you can delete non-editable tokens such as "" and then continue deleting other text after the last character of a string is delete, for example.

**Comment by MajeedKazemi** [comment]
fixed issue with #110 + #852726fe8745486963bed4caca8d063f9ab5328c
