### ISSUE TITLE
Void methods get treated as non-addables for the wrong reason. 

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#75]
Currently, code such as

   while print("abc") 

is not allowed to be added because print() is not addable to while. However, it is not because print() returns void and while only accepts booleans, but because methods that return void get treated as non-addables to most other constructs. The type check never even gets a chance to run in this case. This causes problems for the accuracy of notifications as far as the reason for failure displayed by the notification is concerned. 

Void methods should probably be type-checked like all other method calls that are added to TypedEmptyExpressions.

**Comment by MajeedKazemi** [comment]
I think this would also be fixed with #89
