### ISSUE TITLE
Notifications: Nested expression types need to be recursively checked

### ISSUE THREAD

**Issue by vicchig** [MajeedKazemi/nova-editor#86]
Currently only top level is checked so things like ((123 + 321) + (“abc” + “def”)) ) are possible. Need to look at insertions in the first expression during ((--- + ---) + ("abc" + "def")) and if they would change the expression type to something that is not a string, need to highlight the expression and let the user know. 

This could present challenges with removing the highlight when it is no longer needed.

**Comment by vicchig** [comment]
In addition, currently most operators use EmptyExpr instead of TypedEmptyExpr. This will be significantly easier to implement if they are TypedEmptyExpr. This will require some changes to the Type Checking that is coming from the NotificationSystem in the code because it was written at a time when this solution was not considered yet.

**Comment by MajeedKazemi** [comment]
duplicate #120
