### ISSUE TITLE
Literal buttons to visually add an editable rectangle in the editor

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/nova-editor#90]
Currently, when the user clicks on the *insert number* button, it will visually just remove the hole, but instead the system should display a small rectangle around it that indicates it has to be filled in.

Similar to what Grasshopper does:
![image](https://user-images.githubusercontent.com/57059538/120821834-cb48b880-c523-11eb-82bb-b71578a6bbeb.png)

Interestingly, if the user leaves the inserted number rectangle, Grasshopper will automatically set it to 0 (similar to what we would expect from a String literal.

This visual indicator could be implemented for all editable texts (e.g. variable definition identifiers, for loops identifiers, function definition identifiers, function args, and etc. as well as numbers and texts)

**Comment by MajeedKazemi** [comment]
when defining variables

![image](https://user-images.githubusercontent.com/57059538/120822430-680b5600-c524-11eb-82a2-c8bdaeda4120.png)

if the user clicks on it once (and selects the identifier), an edit icon will appear to its right:
![image](https://user-images.githubusercontent.com/57059538/120822480-735e8180-c524-11eb-9aa2-7f408827367b.png)

**Comment by vicchig** [comment]
Implemented by 5fe041. Can be closed once it is merged.
